Obstacles:
  ob1:
    x: [10, 15, 15, 10, 10]
    y: [2, 2, 15, 15, 2]

StartLoc: [0, 1]
GoalLoc: [20, 15]

VFRRT:
  exploration: 0.75
  initial_lambda: 1
  update_freq: 300

OMPL:
  solve_time: 2.0

Dataset:
  filepath: ../resources/ca_subCA_das_2020010103.nc
  depth: 7
  Index:
    low: 0
    high: 25